name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics-top-langs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          filename: output/github-top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: IVKLD
          template: classic
          base: ""
          config_display: columns
          config_octicon: yes
          config_timezone: Europe/Moscow
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size,percentage
          plugin_languages_colors: github
          plugin_languages_categories: markup,programming
